service:
    name: Monitor

provider:
    name: aws
    runtime: nodejs12.x
    region: ap-northeast-1
    stage: v1
    timeout: 10

resources:
    Resources:
        logTable:
            Type: AWS::DynamoDB::Table
            AttributeDefinitions:
                -
                    AttributeName: value
                    AttributeType: S
                -
                    AttributeName: timestamp
                    AttributeType: N
            KeySchema:
                -
                    AttributeName: value
                    KeyType: HASH
                -
                    AttributeName: timestamp
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
    Outputs:
        UsersTableArn:
            Description: table
            Value:
              'Fn::GetAtt': [usersTable, Arn]
            Export:
              Name: ${self:service}:${opt:stage}:UsersTableArn

plugins:
    - serverless-webpack

custom:
    webpack:
        webpackConfig: 'webpack.config.js'
        packager: 'yarn'
        includeModules: true

functions:
    monitor:
        handler: index.handler
        events:
            - schedule: rate(1 minutes)
